#----------------------------------------------------------------------
# This file was generated by 
#
from wx.lib.embeddedimage import PyEmbeddedImage

get_prev_patch_icon = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABIAAAASCAYAAABWzo5XAAAAYklEQVR4AWMgC4wCByCuxyPP'
    b'AsQqBE2BGvIfh5wCEB8GqaHEoGggfg+SI9cgASBeDhX7T7pBiPB6DOKTbxDCO58pMgg9gCk3'
    b'CBHl1UD8mzKDEMAEiG9D1FCeIHnABpIMRgEAEH8qgMa/MO4AAAAASUVORK5CYII=')

