# ----------------------------------------------------------------------
# This file was generated by
#
from wx.lib.embeddedimage import PyEmbeddedImage

get_add_region_icon = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABIAAAASCAYAAABWzo5XAAAA7klEQVR4Ab3RgQbCUBSA4RBC'
    b'CGEIwxBCCDDEEHqEYdhjhAFCCBBCgBACBNgjBAgQQoCLMAynH6fkdsuG+vngzo573MY/aiFC'
    b'okI0UbkuliggFoMMbXytjzMEW8QYwMcUOwiO8ODMwwVX/elTE9x0mPNmGxQY4rWlei2BIHPd'
    b'psQCdrmyO8DYDxBDMKgxKIUgxLMMYq2TK6Ny9VhzCEHiGtSuMagHQeq8Zo3VIggiPPP1cF5j'
    b'0BoFWvaHPcqKzz9CqedvBTA4wcenxrjijC6chTBqhkDPO4iwguCCPr4W6JriUGIDD5XzkSJT'
    b'MTz8tjvS5lRTy2gdqwAAAABJRU5ErkJggg==')
