# ----------------------------------------------------------------------
# This file was generated by
#
from wx.lib.embeddedimage import PyEmbeddedImage

get_flood_add_icon = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABIAAAASCAYAAABWzo5XAAABAElEQVR4AaXQAWQCYRjH4eEQ'
    b'hhBgCEOAEAYYEAIMAwQYAoRhCMMwhABDGAKEAeAQYAgBQghhOIRw+PYcHXOtk/rxgO/zx3t1'
    b'Qnc0uLgVY86uxStbljxR5+SqTAh7P6wIe0MqlFZjTcqAm8LbiMCc0rEpO1ocq0NgyL/dE+iT'
    b'FTFgwRcd8kYEGhz0RkJEVo9Q0CPrlsALkprEJMTkLQgFc/ISNsQ0i0Pf5G0JBTPylsWhvE92'
    b'RGSNCQWPZF2T0uegBwJd8s/PrEh4JyJrUHbsiBkJdY7VImXC0epsSejytwp9dqypUlqdGYEN'
    b'MXNSAlNqnFREmxHJ3gdtzi6Gy2tCeb/d4Vu1EW5xrgAAAABJRU5ErkJggg==')
