# ----------------------------------------------------------------------
# This file was generated by
#
from wx.lib.embeddedimage import PyEmbeddedImage

get_flood_remove_icon = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABIAAAASCAYAAABWzo5XAAAA2UlEQVR4Ab3UAQTCQBSA4TCE'
    b'EAKEIQQIASAgBAgAAQLAAGEIAcIAAcIAAwAcBggDQAjDEA5hGF4/Lljb7jT6+cDx3J1zA4cW'
    b'Ru+U8XNLHFEYe/hwbowYYjzxgBhnDNHZBDkqhJjW1iIIMtuwBCWWaGsDs7PmVhAEsBVBMMdX'
    b'J2h4sDWD4FB/JwoaCq5pFFBY1Afd4Nq9PujTFaXj0Uao2u5zC8EOtsKuy/aQQsO3vPgKMVrz'
    b'8YJu2NkQAUrkGKMzHykEBRQyVBAkmMApD2tE0MYF6z9/Iz0+tjf78EFtnv7rrQAAAABJRU5E'
    b'rkJggg==')
