# ----------------------------------------------------------------------
# This file was generated by
#
from wx.lib.embeddedimage import PyEmbeddedImage

get_next_patch_icon = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABIAAAASCAYAAABWzo5XAAAAWklEQVR4AWMgC4wCGQLy9UDs'
    b'AGESVrgeiEVwyP+HqiFsEFTxcyB2p9wgBJ4MxByUGYTAl4HYgDKDEN70ptAgRMCTa9BnIE6n'
    b'NLBPA7EKpdGvA8QslCZITDAKAOXmKXB2GeaxAAAAAElFTkSuQmCC')
