# ----------------------------------------------------------------------
# This file was generated by
#
from wx.lib.embeddedimage import PyEmbeddedImage

get_no_root_icon = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABIAAAASCAYAAABWzo5XAAAA0ElEQVR4AbWRIQyDQAxFTyDx'
    b'wQcffCbwFh+8mpicxGcCiUQi53NiAq8mT0zMBzGBYF+UpPk5GhA0eaZtXtrWnR05aMAIguDB'
    b'HWR7BAlowQyWDX4iNCXeEDD9lqgDyyEikxXUMIAb5WZQgxetmVnTlJK/KkkludqaKlBxApdV'
    b'piRV5BFeixaGZCzRBFOk16E1mY8WfQ1JRWuyaNSiXhf5JrQmf7PRopKKj8hNJukbaPLcUTyl'
    b'eITWRSIF7wMSDxIQjXTnZJ0l4Zv19M0ggsKdGX9ap6mHPjrnrQAAAABJRU5ErkJggg==')
