#----------------------------------------------------------------------
# This file was generated by 
#
from wx.lib.embeddedimage import PyEmbeddedImage

get_remove_region_icon = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABIAAAASCAYAAABWzo5XAAAA40lEQVR4Ab3RAUdDYRSA4RCG'
    b'IQwX4WIYhiHAEBdhP2EY9jPCBYQwQAgDhDBAgH7CAAGGYYCLMFycnlhofdYH9fKAw3E4Z/9R'
    b'h4rZwZhzsuuxYE8caajpcrIBG4InpgwpmfBMsKYgWcGWHROS6YZ31iQvW7JnxG/NCOrUNS33'
    b'5PZCc/yAKcGQ3OYEYyTVBF8teE0zk0YEs9SiLrmLLgnm6TPzqwgqJJUEd+T2yJ4O31rRZr7/'
    b'ipYFP+rT8EaJkl2zY0OPZGOag1v6fHZBxQPBlgEn67MiElqWFGRXMqc+mFLwt30A5MdLX59U'
    b'9pgAAAAASUVORK5CYII=')

