# ----------------------------------------------------------------------
# This file was generated by
#
from wx.lib.embeddedimage import PyEmbeddedImage

get_threshold_icon = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABIAAAASCAYAAABWzo5XAAAAX0lEQVR4AWMY8qAfjAkAAyB2'
    b'wIENoGr2A/F5dHEEQCj6jwPvx6FmPw1dhGmoAXlhhOnN/eTHCMKA9xAaIY4D99PAIMq9Rjiw'
    b'yQ1gAyKj3IHUBLmfhIRKuYtIz6hDDgAAH9ZDOREJ0a8AAAAASUVORK5CYII=')
