#----------------------------------------------------------------------
# This file was generated by 
#
from wx.lib.embeddedimage import PyEmbeddedImage

get_zoom_out_tool_icon = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABIAAAASCAYAAABWzo5XAAAAtElEQVR4AdXMAWQCUQCA4SGE'
    b'4QAwBBiGYQgQAWAACCEECBAgAIRDAIAAhxBCAAghHCCEEEIIIby+EBy8S6F+PoD/4y2q0iJl'
    b'RIeEu/omJ3BgT2BLnVJ9smZLk1t/5Oz5IlqPQJ1iNU6kRMvIufZLA5CmLIk2Y8G1NgNAGrMh'
    b'2pAjCcUqbJgQ7YczGdXCJCXQpFRdzqxJGbIisKNF6RrMOXBiwT99Aj0eqkL20rMdyTNmNV64'
    b'C2XuMSz/5Fg3AAAAAElFTkSuQmCC')

