# ----------------------------------------------------------------------
# This file was generated by
#
from wx.lib.embeddedimage import PyEmbeddedImage

get_zoom_in_tool_icon = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABIAAAASCAYAAABWzo5XAAAAwElEQVR4AdXMAWQCUQCA4SGE'
    b'4QAwBBiGYQhwBIABIIRhgAMMMACEwwAQBjgMwzAMEIZwgBBCCCGE8PoeIuBdCvXzAfw3V1Gb'
    b'PiUfvJBxVPfUBFYsCczp0qhbpszpse+JmiV3JCsIdIk9MiDWYUNJsor6YFIwIif2zT/JfhgT'
    b'GzDij3din8xINmRNRiw/mLSY8UWyB7ZUtJFMKAn0aNQrW6aUDJkQWNCncTm/rNgw5pk3AgUn'
    b'1aK66NmC7ByzDhfcDmecM2gsTgRxAAAAAElFTkSuQmCC')
